name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install --upgrade pip
          pip install coverage

      - name: Setup config and secret files
        run: |
          mv secrets.toml.template secrets.toml
      - name: Testing
        run: |
          coverage run -m unittest discover ./tests

      - name: Coverage
        run: |
          coverage report -m
